jobs:
  - name: cursoryx_build_x11
    plan:
      - task: cursoryx_build_x11_task
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: docker_registry:443/nullgemm/cursoryx_image_gcc
              ca_certs: ((docker_registry_certs))
              tag: latest
          params:
            GIT_REPO_URL: cursoryx_image_gcc
          run:
            path: /scripts/build_x11.sh
