jobs:
  - name: cursoryx_build_x11
    plan:
      - task: cursoryx_build_x11_task
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: docker_registry:443/nullgemm/cursoryx_image_x11_gcc
              ca_certs: ((docker_registry_certs))
              tag: latest
          params:
            GIT_REPO_URL: cursoryx_image_x11_gcc
          run:
            path: /scripts/build_x11.sh
  - name: cursoryx_build_appkit_osxcross
    plan:
      - task: cursoryx_build_appkit_osxcross_task
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: docker_registry:443/nullgemm/cursoryx_image_appkit_osxcross
              ca_certs: ((docker_registry_certs))
              tag: latest
          params:
            GIT_REPO_URL: cursoryx_image_appkit_osxcross
          run:
            path: /scripts/build_appkit.sh
  - name: cursoryx_build_appkit_native
    plan:
      - task: cursoryx_build_appkit_software_task
        config:
          platform: darwin
          run:
            path: /bin/bash
            args: ["--login", "/Users/nullgemm/Documents/concourse/bin/cursoryx_scripts_appkit_native/build.sh"]
